# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakelinkshub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fakelinkshub.Urls')),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fakelinkshub.Users')),
            ],
        ),
    ]
