# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fakelinkshub', '0003_auto_20180506_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='id',
        ),
        migrations.AddField(
            model_name='repo',
            name='repo_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
