# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakelinkshub', '0004_auto_20180507_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='repo',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='url',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
