# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 11:46
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fakelinkshub', '0005_auto_20180507_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSource',
            fields=[
                ('resource_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='reason',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url_title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlsource',
            name='url_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fakelinkshub.Url'),
        ),
    ]
