#!c:\users\gsrungarapu\desktop\internet-trustworth-master\env\scripts\python.exe

# We should have absolute imports here
from tld.commands.update_tld_names import main


if __name__ == "__main__":
    main()
